### ISSUE TITLE
Attach task queue name as metric label

### ISSUE THREAD

**Issue by dimrozakis** [zerok/celery-prometheus-exporter#19] opened 2017-11-08 02:46 UTC
Is something like this possible? Is that information included in the task's/event's metadata?

**Comment by zerok** [comment] 2017-11-08 07:13
Looking at the Task class I see at least a `queue` field. Not sure if this contains the information you're looking for in all situations, though. Sadly, I currently don't have enough time to look into it, but I've added it to my todo list 😄

**Comment by javabrett** [comment] 2018-08-15 05:59
I think this can safely be closed as a duplicate of #31.

**Comment by zerok** [comment] 2018-08-16 15:11
Agreed 🙂

**Closed by zerok** 2018-08-16 15:11 UTC
